// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwpvksvvcctthwnrurtr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3cHZrc3Z2Y2N0dGh3bnJ1cnRyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUxNjg2NDcsImV4cCI6MjA2MDc0NDY0N30.wUq0cKIjnvXUJ5LejKqf31OuiovWe0-aaOTott1KV_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);